export const ALL_PRODUCTS_REQUEST="ALL_PRODUCTS_REQUEST";
export const ALL_PRODUCTS_SUCCESS="ALL_PRODUCTS_SUCCESS";
export const ALL_PRODUCTS_FAIL="ALL_PRODUCTS_FAIL";

export const ADMIN_ALL_PRODUCTS_REQUEST="ADMIN_ALL_PRODUCTS_REQUEST";
export const ADMIN_ALL_PRODUCTS_SUCCESS="ADMIN_ALL_PRODUCTS_SUCCESS";
export const ADMIN_ALL_PRODUCTS_FAIL="ADMIN_ALL_PRODUCTS_FAIL";

export const NEW_REVIEW_REQUEST="NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS="NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_FAIL="NEW_REVIEW_FAIL";
export const NEW_REVIEW_RESET="NEW_REVIEW_RESET";

export const NEW_PRODUCT_REQUEST="NEW_PRODUCT_REQUEST";
export const NEW_PRODUCT_SUCCESS="NEW_PRODUCT_SUCCESS";
export const NEW_PRODUCT_FAIL="NEW_PRODUCT_FAIL";
export const NEW_PRODUCT_RESET="NEW_PRODUCT_RESET";

export const PRODUCT_DETAILS_REQUEST="PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS="PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL="PRODUCT_DETAILS_FAIL";
export const CLEAR_ERRORS="CLEAR_ERRORS";
